version: "3.8"

services:
  elainabot:
    build: .
    container_name: elainabot_v2
    restart: unless-stopped
    ports:
      - "5200:5200"
    volumes:
      - ./config:/app/config
      - ./plugins:/app/plugins
      - ./modules:/app/modules
      - ./log:/app/log
    environment:
      - TZ=Asia/Shanghai
    tty: true
    stdin_open: true
